network:
  version: 2
  ethernets:
    ens160:
      addresses:
        - 10.0.0.10/24
      routes:
        - to: 0.0.0.0
          via: 10.0.0.10.54
  tunnels:
    gre-tunnel:
      mode: gre
      remote: 20.0.0.10
      local: 30.0.0.10
      addresses:
        - 192.168.1.2/30
      routes:
        - to: 192.168.1.0/30
          via: 192.168.1.1
